# **Decision Tree Regressor**

In [1]:
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#import the boston dataset
from sklearn.datasets import load_boston

boston = load_boston()

In [3]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [4]:
#create the dependent and independent features
X = pd.DataFrame(boston.data, columns = boston.feature_names)
y = boston.target

In [5]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [6]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [7]:
#split into train and test the data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 47)

In [8]:
#import DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor

#define the model
regressor = DecisionTreeRegressor()

In [9]:
#fit the model
regressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [10]:
#predict the model
y_pred = regressor.predict(X_test)
y_pred

array([20.9, 31.1, 21. , 27.9, 23.7, 23.8, 15. , 29.8, 21. , 21.4, 24.6,
       28.6, 20.4, 28.7, 23.3, 19.9, 34.6, 17.5,  5. , 14.8, 32. , 20. ,
       50. , 14.3, 21.6, 27.5, 21.2, 20.4, 16.7, 22.3, 13.8, 23.1, 19.1,
       10.5, 30.1, 19.6, 14.3, 23.4, 19.7, 19.6, 25. , 22.8, 50. , 21.6,
       33.8, 15. , 15. , 22.8, 50. , 22.9, 24.8, 21.2,  5.6, 23.2, 13.8,
       18.7, 22.5, 11.8, 10.5, 29.9, 23.2, 20. , 15. , 23.8, 50. , 18.4,
       22. , 26.4, 23.4, 19.6, 21.7, 18.5, 26.5, 21.2, 29.9, 15.6, 21.7,
       27.1, 12.5, 27.5, 10.5, 33.4, 43.8, 21.7, 37.3, 13.3, 24.8, 22.4,
       27.5, 22. , 10.4, 20.4, 14.5, 20. , 29. , 15.6, 46.7, 33.1,  8.4,
       21.7, 26.6, 17.3, 18.6, 15.6, 20. , 29.9, 18.3, 19.1, 13.4, 19.5,
       13.8, 23.2, 37.3, 20.4, 10.4, 20. , 23.8, 23.5, 45.4, 19.4, 11.8,
       16.2, 28.5, 21.2, 10.8, 18.9, 37.2,  8.5, 29.9, 17.1, 17.5, 10.4,
       19.4, 22.5, 12.5, 31.5, 27.5, 19.3, 19.6, 11.8, 38.7, 20.6,  7.2,
       18.3, 21.9, 50. , 17.6, 14.9, 23.4, 22.4, 23

In [11]:
#calculate the accuracy by r2 score for regression model
from sklearn.metrics import r2_score
score = r2_score(y_pred, y_test)
score

0.6418256225011891

In [18]:
#now by using hyperparameter tuning
parameters = {
    "criterion" : ["squared_error", "friedman_mse", "absolute_error", "poisson"],
    "splitter" : ["best", "random"],
    "max_depth" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "max_features" : ["auto", "sqrt", "log2"]
}

In [19]:
#define the model
regressor = DecisionTreeRegressor()

In [20]:
#import GridSearchCV and warnings
import warnings
warnings.filterwarnings("ignore")

#import the GridSearchCV
from sklearn.model_selection import GridSearchCV

#define the GridSerchCV
regressor_cv = GridSearchCV(regressor, param_grid = parameters, cv = 5, scoring = "neg_mean_squared_error")

In [21]:
#fit the model
regressor_cv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='neg_mean_squared_error')

In [22]:
regressor_cv.best_params_

{'criterion': 'friedman_mse',
 'max_depth': 8,
 'max_features': 'auto',
 'splitter': 'random'}

In [23]:
#predict with the model
y_pred = regressor_cv.predict(X_test)
y_pred

array([18.4       , 31.69090909, 18.85      , 31.69090909, 23.508     ,
       20.31724138, 17.        , 33.8       , 32.2       , 20.31724138,
       23.508     , 26.675     , 18.445     , 23.7       , 50.        ,
       15.2       , 31.69090909, 20.34285714,  9.        , 18.445     ,
       32.2       , 18.445     , 37.6       , 18.26      , 28.25      ,
       13.3       , 20.34285714, 22.18571429, 20.31724138, 23.66      ,
       14.5       , 21.42857143, 20.31724138,  9.        , 25.9       ,
       21.42857143, 18.26      , 23.508     , 20.34285714, 21.42857143,
       23.508     , 25.28      , 50.        , 20.34285714, 23.6       ,
       50.        , 13.34285714, 20.65      , 36.1       , 23.508     ,
       23.508     , 22.18571429,  9.        , 22.18571429, 13.8       ,
       25.28      , 22.18571429,  9.74444444,  9.        , 25.32      ,
       13.34285714, 21.225     , 20.31724138, 20.31724138, 50.        ,
       20.65      , 21.42857143, 23.508     , 23.508     , 25.28

In [24]:
#find the accurarcy with r2 score
score = r2_score(y_pred, y_test)

In [25]:
score

0.7182646927486651